/**
 * Represents a single legal citation used in the generated document.
 */
export interface LegalCitation {
  /** Name of the law or regulation, e.g. 《水法》 */
  title: string;
  /** Original text of the cited article */
  articleText: string;
}

/**
 * Global state shared between LangGraph nodes for WaterDocument processing.
 */
export interface WaterDocumentState {
  /** Raw input material provided by the user (source text). */
  rawInput: string;
  /** Draft document content generated by the AI agent. */
  documentContent: string;
  /** List of legal citations that support the current draft. */
  legalCitations: LegalCitation[];
  /** Current processing status in the document lifecycle. */
  status: 'idle' | 'drafting' | 'reviewing' | 'exporting' | 'completed';
  /** Number of times the document has been revised, used for LangGraph loop control. */
  revisionCount: number;
  /** Identifier used to persist and track this document/thread across requests. */
  threadId: string;
  /** Index signature required by LangGraph's StateDefinition constraint. */
  [key: string]: unknown;
}

